language: ruby
rvm:
  - 2.4.2
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: '3db9a9f19861b4b7c6869660a796b0eb0178f5cf508204db55007834dd208006'
before_install: gem install bundler -v 1.10.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - "bundle exec rake db:drop RAILS_ENV=test"
  - "bundle exec rake db:setup RAILS_ENV=test"
  - "yarn"
  - "RAILS_ENV=test bin/webpack"

after_success:
- bundle exec codeclimate-test-reporter
